// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package be.wijverbouwen.model;

import be.wijverbouwen.model.Part;
import be.wijverbouwen.model.PartDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect PartDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PartDataOnDemand: @Component;
    
    private Random PartDataOnDemand.rnd = new SecureRandom();
    
    private List<Part> PartDataOnDemand.data;
    
    public Part PartDataOnDemand.getNewTransientPart(int index) {
        Part obj = new Part();
        setAmountPayed(obj, index);
        setDescription(obj, index);
        setImageSource(obj, index);
        setPartName(obj, index);
        setTotalCost(obj, index);
        return obj;
    }
    
    public void PartDataOnDemand.setAmountPayed(Part obj, int index) {
        double amountPayed = new Integer(index).doubleValue();
        obj.setAmountPayed(amountPayed);
    }
    
    public void PartDataOnDemand.setDescription(Part obj, int index) {
        String description = "description_" + index;
        obj.setDescription(description);
    }
    
    public void PartDataOnDemand.setImageSource(Part obj, int index) {
        String imageSource = "imageSource_" + index;
        obj.setImageSource(imageSource);
    }
    
    public void PartDataOnDemand.setPartName(Part obj, int index) {
        String partName = "partName_" + index;
        if (partName.length() > 50) {
            partName = partName.substring(0, 50);
        }
        obj.setPartName(partName);
    }
    
    public void PartDataOnDemand.setTotalCost(Part obj, int index) {
        double totalCost = new Integer(index).doubleValue();
        obj.setTotalCost(totalCost);
    }
    
    public Part PartDataOnDemand.getSpecificPart(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Part obj = data.get(index);
        Long id = obj.getId();
        return Part.findPart(id);
    }
    
    public Part PartDataOnDemand.getRandomPart() {
        init();
        Part obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Part.findPart(id);
    }
    
    public boolean PartDataOnDemand.modifyPart(Part obj) {
        return false;
    }
    
    public void PartDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Part.findPartEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Part' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Part>();
        for (int i = 0; i < 10; i++) {
            Part obj = getNewTransientPart(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
