// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package be.wijverbouwen.model;

import be.wijverbouwen.model.ReservationDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ReservationDataOnDemand_Roo_Configurable {
    
    declare @type: ReservationDataOnDemand: @Configurable;
    
}
