// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package be.wijverbouwen.model;

import be.wijverbouwen.model.PartDataOnDemand;
import be.wijverbouwen.model.Reservation;
import be.wijverbouwen.model.ReservationDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect ReservationDataOnDemand_Roo_DataOnDemand {
    
    declare @type: ReservationDataOnDemand: @Component;
    
    private Random ReservationDataOnDemand.rnd = new SecureRandom();
    
    private List<Reservation> ReservationDataOnDemand.data;
    
    @Autowired
    private PartDataOnDemand ReservationDataOnDemand.partDataOnDemand;
    
    public Reservation ReservationDataOnDemand.getNewTransientReservation(int index) {
        Reservation obj = new Reservation();
        setAmountPayed(obj, index);
        setAmountReserved(obj, index);
        setEmail(obj, index);
        setName(obj, index);
        setPayed(obj, index);
        setPhone(obj, index);
        return obj;
    }
    
    public void ReservationDataOnDemand.setAmountPayed(Reservation obj, int index) {
        double amountPayed = new Integer(index).doubleValue();
        obj.setAmountPayed(amountPayed);
    }
    
    public void ReservationDataOnDemand.setAmountReserved(Reservation obj, int index) {
        double amountReserved = new Integer(index).doubleValue();
        obj.setAmountReserved(amountReserved);
    }
    
    public void ReservationDataOnDemand.setEmail(Reservation obj, int index) {
        String email = "foo" + index + "@bar.com";
        if (email.length() > 50) {
            email = email.substring(0, 50);
        }
        obj.setEmail(email);
    }
    
    public void ReservationDataOnDemand.setName(Reservation obj, int index) {
        String name = "name_" + index;
        if (name.length() > 50) {
            name = name.substring(0, 50);
        }
        obj.setName(name);
    }
    
    public void ReservationDataOnDemand.setPayed(Reservation obj, int index) {
        Boolean payed = Boolean.TRUE;
        obj.setPayed(payed);
    }
    
    public void ReservationDataOnDemand.setPhone(Reservation obj, int index) {
        String phone = "phone_" + index;
        if (phone.length() > 20) {
            phone = phone.substring(0, 20);
        }
        obj.setPhone(phone);
    }
    
    public Reservation ReservationDataOnDemand.getSpecificReservation(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Reservation obj = data.get(index);
        Long id = obj.getId();
        return Reservation.findReservation(id);
    }
    
    public Reservation ReservationDataOnDemand.getRandomReservation() {
        init();
        Reservation obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Reservation.findReservation(id);
    }
    
    public boolean ReservationDataOnDemand.modifyReservation(Reservation obj) {
        return false;
    }
    
    public void ReservationDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Reservation.findReservationEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Reservation' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Reservation>();
        for (int i = 0; i < 10; i++) {
            Reservation obj = getNewTransientReservation(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
